### DISCUSSION TITLE
monitoring/prometheus-scrape-config

### DISCUSSION THREAD

**Discussion by giscus** [imroc/tke-guide#7] [General]
https://imroc.cc/tke/monitoring/prometheus-scrape-config

**Comment by gotosre** [comment]
佬，最最最主流的不应该是prometheus crd的方式吗？
在crd制定additionalScrapeConfig？https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

**Comment by gotosre** [comment]
```yaml
```

**Reply by gotosre** [reply]
```
    - job_name: eks
      honor_timestamps: true
      metrics_path: '/metrics'
      params:
        collect[]: ['ipvs']
```
